### ISSUE TITLE
The Holy Court - Case 1

### ISSUE THREAD

**Issue by Leahxx** [dotnetbattleroyale/discussion#1]
Topic: Inviting Sleepy & Mango

The question is posed to the court as follows:
**Should we do it?**

**Comment by Sid-003** [comment]
Sí ~~sabes que ya llevo un rato mirándote~~

**Comment by Kyle-Undefined** [comment]
to be part of the org? idk, idc

**Comment by purpledank** [comment]
No

**Comment by Kyle-Undefined** [comment]
inviting them to what then?

**Comment by trinitrot0luene** [comment]
Absolutely, categorically, not.

**Comment by Leahxx** [comment]
Reopening to hear Mango's case

**Comment by Adomix** [comment]
Ok so Leah reopened so I am obligated to state my case I guess.

I'd like to apologize to Sid - your mother is not a black bitch. In fact, I bet she is a very bright woman and you are a good kid.

Also trinitrot, you caught me in a bad mood I apologize.

And just so you guys know I did start anger management a few days ago 🙏.

**Comment by Leahxx** [comment]
cc @Sid-003 @purpledank @trinitrot0luene
